// <auto-generated />
namespace MrSimonAcademy2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updategroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updategroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202009271223001_update group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
